### ISSUE TITLE
Example error with ERA5

### ISSUE THREAD

**Issue by Mel41127** [MET-OM/metocean-api#15]
Hi,
I installed metocean-api and metocean-stats with anaconda (forge) on Windows and I have an error message when trying to run the example in Spyder (copy-paste the script here :  https://github.com/MET-OM/metocean-stats/blob/main/examples/example_ERA5_stats.py)
It says : ERA5_ts() got an unexpected keyword argument 'save_nc'

Could anyone help me understand the issue please ?

**Comment by KonstantinChri** [comment]
Hi,
Please try to update the metocean-api using its lastest version. I re-run the example for ERA5 https://github.com/MET-OM/metocean-api/blob/main/examples/example_import_ERA5.py without any issue.
