### ISSUE TITLE
Dependency on Python 3.12 not stated in environment.yml

### ISSUE THREAD

**Issue by davidosterberg** [MET-OM/metocean-api#47]
Library no longer works with Python 3.11. This is the default python in for example Debian 12.

![image](https://github.com/user-attachments/assets/0d086705-6340-4189-9c81-4d791d6083d3)

1) typing.overide was added in 3.12 (https://peps.python.org/pep-0698/) is it intentional to break the library because of a typing feature. Seems like the benefits do not justify the inconvenience to users
2) environment.yml does not state the dependency, so the library will download fine, but will be broken.

**Comment by lassebje** [comment]
@davidosterberg  This is already being adressed in this pull request https://github.com/MET-OM/metocean-api/pull/45. It was a mistake to rely on python 12+ specific syntax. This should have been caught by the CI-system.

**Comment by lassebje** [comment]
Suggest to won't fix this issue now as the @override annotations has been removed in main.
