### ISSUE TITLE
Cacheless loading?

### ISSUE THREAD

**Issue by ketilt** [MET-OM/metocean-api#9]
Is there a way to avoid local files being stored when using `import_data`?

Using `df_ts.import_data(save_csv=False)`, but cache is still being saved.

Although small in size, I am deploying this on a service with multiple users, and I am worried about file bloat on the system.

(No need to add such functionality if it's a hassle, I could always run a file cleanup using the `os` package in python)

**Comment by KonstantinChri** [comment]
Hi,
Sorry for the late reply. It is now fixed in version 1.1.5. By default, the cache is cleaned.
